export const STATUSES = [
  "прибыл",
  "в обработке",
  "готов к отправке",
  "отправлен",
  "отменен",
  "поломка оборудования",
];

export interface Container {
  id: string;
  name: string;
  country: string;
  weight: number;
  status: string;
  arrivalDate?: string;  
  sentDate?: string;         
  direction?: string;
  cargoType?: string;
  zone?: string;
  shift?: string;
  loadCapacity?: number;
  urgency?: string;
  equipmentAvailable?: boolean;
}

export const initialContainers: Container[] = [
  {
    id: "1",
    name: "CONT-001",
    country: "Китай",
    weight: 15.5,
    status: "прибыл",
    arrivalDate: "2025-12-01",
    sentDate: "2025-12-05",
    direction: "Восток",
    cargoType: "Электроника",
    zone: "A1",
    shift: "День",
    loadCapacity: 80,
    urgency: "средняя",
    equipmentAvailable: true,
  },
  {
    id: "2",
    name: "CONT-002",
    country: "Казахстан",
    weight: 22.3,
    status: "прибыл",
    arrivalDate: "2025-12-02",
    sentDate: "2025-12-06",
    direction: "Север",
    cargoType: "Продукты",
    zone: "B3",
    shift: "Ночь",
    loadCapacity: 60,
    urgency: "низкая",
    equipmentAvailable: false,
  },
  {
    id: "3",
    name: "CONT-003",
    country: "Казахстан",
    weight: 18.7,
    status: "в обработке",
    arrivalDate: "2025-12-03",
    sentDate: "2025-12-07",
    direction: "Юг",
    cargoType: "Одежда",
    zone: "C2",
    shift: "День",
    loadCapacity: 75,
    urgency: "высокая",
    equipmentAvailable: true,
  },
  {
    id: "4",
    name: "CONT-004",
    country: "Кыргызстан",
    weight: 20.1,
    status: "в обработке",
    arrivalDate: "2025-12-04",
    sentDate: "2025-12-08",
    direction: "Запад",
    cargoType: "Металл",
    zone: "D1",
    shift: "Ночь",
    loadCapacity: 50,
    urgency: "средняя",
    equipmentAvailable: true,
  },
  {
    id: "5",
    name: "CONT-005",
    country: "Казахстан",
    weight: 16.8,
    status: "готов к отправке",
    arrivalDate: "2025-12-05",
    sentDate: "2025-12-09",
    direction: "Восток",
    cargoType: "Машины",
    zone: "E3",
    shift: "День",
    loadCapacity: 90,
    urgency: "высокая",
    equipmentAvailable: false,
  },
  {
    id: "6",
    name: "CONT-006",
    country: "Китай",
    weight: 19.4,
    status: "готов к отправке",
    arrivalDate: "2025-12-06",
    sentDate: "2025-12-10",
    direction: "Север",
    cargoType: "Химия",
    zone: "F2",
    shift: "Ночь",
    loadCapacity: 70,
    urgency: "средняя",
    equipmentAvailable: true,
  },
  {
    id: "7",
    name: "CONT-007",
    country: "Узбекистан",
    weight: 21.2,
    status: "отправлен",
    arrivalDate: "2025-12-07",
    sentDate: "2025-12-11",
    direction: "Юг",
    cargoType: "Продукты",
    zone: "G1",
    shift: "День",
    loadCapacity: 85,
    urgency: "низкая",
    equipmentAvailable: false,
  },
  {
    id: "8",
    name: "CONT-008",
    country: "Казахстан",
    weight: 17.9,
    status: "отправлен",
    arrivalDate: "2025-12-08",
    sentDate: "2025-12-12",
    direction: "Запад",
    cargoType: "Электроника",
    zone: "H2",
    shift: "Ночь",
    loadCapacity: 60,
    urgency: "высокая",
    equipmentAvailable: true,
  },
  {
    id: "9",
    name: "CONT-009",
    country: "Казахстан",
    weight: 14.6,
    status: "отменен",
    arrivalDate: "2025-12-09",
    sentDate: "2025-12-13",
    direction: "Восток",
    cargoType: "Одежда",
    zone: "I3",
    shift: "День",
    loadCapacity: 55,
    urgency: "средняя",
    equipmentAvailable: true,
  },
  {
    id: "10",
    name: "CONT-010",
    country: "Китай",
    weight: 23.1,
    status: "поломка оборудования",
    arrivalDate: "2025-12-10",
    sentDate: "2025-12-14",
    direction: "Север",
    cargoType: "Металл",
    zone: "J1",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
  },
  {
    id: "11",
    name: "CONT-011",
    country: "Узбекистан",
    weight: 23.1,
    status: "отправлен",
    arrivalDate: "2025-12-07",
    sentDate: "2025-12-10",
    direction: "Север",
    cargoType: "Металл",
    zone: "J1",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
  },
  {
    id: "12",
    name: "CONT-012",
    country: "Китай",
    weight: 20,
    status: "отправлен",
    arrivalDate: "2025-11-25",
    sentDate: "2025-11-29",
    direction: "Север",
    cargoType: "Металл",
    zone: "J1",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
  },
   {
    id: "13",
    name: "CONT-013",
    country: "Китай",
    weight: 25,
    status: "отправлен",
    arrivalDate: "2025-11-20",
    sentDate: "2025-11-20",
    direction: "Север",
    cargoType: "Металл",
    zone: "J1",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
  },
];
