import { int } from "zod";
import { ZoneType } from "./zone";

export const STATUSES = [
  { id: "arrived", label: "прибыл" },
  { id: "processing", label: "в обработке" },
  { id: "ready_to_ship", label: "готов к отправке" },
  { id: "shipped", label: "отправлен" },
  { id: "canceled", label: "отменен" },
  { id: "equipment_broken", label: "поломка оборудования" },
];

export const VISIBLE_STATUSES = STATUSES.slice(0, 3);
export const HISTORY_STATUSES = STATUSES.slice(3);

export interface GreenListContainer {
  container_number: "9667900";
  destination: "алматы-1";
  size: "40";
  country_code: "KZ";
  arrival_date: "20.12";
  customs_control_release_date: "21.12";
  delivery_date: "28.12";
}

export interface Container {
  id: string;
  name: string;
  countryFrom?: string;
  countryTo: string;
  weight: number;
  status: string;
  arrivalDate?: string;
  sentDate?: string;
  sentTime?: string;
  direction?: string;
  cargoType?: string;
  // zone?: [
  //   id: string,
  //   type: ZoneType,
  //   occupancy: number,
  //   containers: string[],
  //   percentage?: number
  // ];
  zone?: string;
  shift?: string;
  loadCapacity?: number;
  urgency?: string;
  equipmentAvailable?: boolean;
  forwarder?: string;
}

export const initialContainers: Container[] = [
  {
    id: "1",
    name: "CONT-001",
    countryTo: "Казахстан",
    weight: 15.5,
    status: "в обработке",
    arrivalDate: "2025-12-01",
    sentDate: "2025-12-05",
    sentTime: "09:30",
    direction: "Восток",
    cargoType: "Электроника",
    zone: "45",
    shift: "День",
    loadCapacity: 80,
    urgency: "средняя",
    equipmentAvailable: true,
    countryFrom: "Китай",
    forwarder: "KTZ Express",
  },
  {
    id: "2",
    name: "CONT-002",
    countryTo: "Казахстан",
    weight: 22.3,
    status: "прибыл",
    arrivalDate: "2025-12-02",
    sentDate: "2025-12-06",
    sentTime: "10:15",
    direction: "Север",
    cargoType: "Продукты",
    zone: "63",
    shift: "Ночь",
    loadCapacity: 60,
    urgency: "низкая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "KTZ Express",
  },
  {
    id: "3",
    name: "CONT-003",
    countryTo: "Казахстан",
    weight: 18.7,
    status: "в обработке",
    arrivalDate: "2025-12-03",
    sentDate: "2025-12-07",
    sentTime: "14:45",
    direction: "Юг",
    cargoType: "Одежда",
    zone: "199",
    shift: "День",
    loadCapacity: 75,
    urgency: "высокая",
    equipmentAvailable: true,
    countryFrom: "Китай",
    forwarder: "KTZ Express",
  },
  {
    id: "4",
    name: "CONT-004",
    countryTo: "Кыргызстан",
    weight: 20.1,
    status: "в обработке",
    arrivalDate: "2025-12-04",
    sentDate: "2025-12-08",
    sentTime: "08:00",
    direction: "Запад",
    cargoType: "Металл",
    zone: "87",
    shift: "Ночь",
    loadCapacity: 50,
    urgency: "средняя",
    equipmentAvailable: true,
    countryFrom: "Китай",
    forwarder: "КеденТрансСервис",
  },
  {
    id: "5",
    name: "CONT-005",
    countryTo: "Узбекистан",
    weight: 16.8,
    status: "в обработке",
    arrivalDate: "2025-12-05",
    sentDate: "2025-12-09",
    sentTime: "13:20",
    direction: "Восток",
    cargoType: "Машины",
    zone: "33",
    shift: "День",
    loadCapacity: 90,
    urgency: "высокая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "КеденТрансСервис",
  },
  {
    id: "6",
    name: "CONT-006",
    countryTo: "Узбекистан",
    weight: 19.4,
    status: "в обработке",
    arrivalDate: "2025-12-06",
    sentDate: "2025-12-10",
    sentTime: "16:00",
    direction: "Север",
    cargoType: "Химия",
    zone: "45",
    shift: "Ночь",
    loadCapacity: 70,
    urgency: "средняя",
    equipmentAvailable: true,
    countryFrom: "Китай",
    forwarder: "КеденТрансСервис",
  },
  {
    id: "7",
    name: "CONT-007",
    countryTo: "Узбекистан",
    weight: 21.2,
    status: "в обработке",
    arrivalDate: "2025-12-07",
    sentDate: "2025-12-15",
    sentTime: "11:10",
    direction: "Юг",
    cargoType: "Продукты",
    zone: "22",
    shift: "День",
    loadCapacity: 85,
    urgency: "низкая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "КеденТрансСервис",
  },
  {
    id: "8",
    name: "CONT-008",
    countryTo: "Казахстан",
    weight: 17.9,
    status: "в обработке",
    arrivalDate: "2025-12-08",
    sentDate: "2025-12-12",
    sentTime: "09:50",
    direction: "Запад",
    cargoType: "Электроника",
    zone: "10",
    shift: "Ночь",
    loadCapacity: 60,
    urgency: "высокая",
    equipmentAvailable: true,
    countryFrom: "Китай",
    forwarder: "Сборная",
  },
  {
    id: "9",
    name: "CONT-009",
    countryTo: "Казахстан",
    weight: 14.6,
    status: "отправлен",
    arrivalDate: "2025-12-09",
    sentDate: "2025-12-13",
    sentTime: "18:30",
    direction: "Восток",
    cargoType: "Одежда",
    zone: "82",
    shift: "День",
    loadCapacity: 55,
    urgency: "средняя",
    equipmentAvailable: true,
    countryFrom: "Китай",
    forwarder: "Сборная",
  },
  {
    id: "10",
    name: "CONT-010",
    countryTo: "Россия",
    weight: 23.1,
    status: "в обработке",
    arrivalDate: "2025-12-10",
    sentDate: "2025-12-14",
    sentTime: "07:40",
    direction: "Север",
    cargoType: "Металл",
    zone: "29",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "Сборная",
  },
  {
    id: "11",
    name: "CONT-011",
    countryTo: "Узбекистан",
    weight: 23.1,
    status: "в обработке",
    arrivalDate: "2025-12-07",
    sentDate: "2025-12-10",
    sentTime: "12:00",
    direction: "Север",
    cargoType: "Металл",
    zone: "91",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "Сборная",
  },
  {
    id: "12",
    name: "CONT-012",
    countryTo: "Кыргызстан",
    weight: 20,
    status: "в обработке",
    arrivalDate: "2025-11-25",
    sentDate: "2025-11-29",
    sentTime: "15:25",
    direction: "Север",
    cargoType: "Металл",
    zone: "39",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "КеденТрансСервис",
  },
  {
    id: "13",
    name: "CONT-013",
    countryTo: "Казахстан",
    weight: 25,
    status: "отправлен",
    arrivalDate: "2025-11-20",
    sentDate: "2025-11-20",
    sentTime: "06:55",
    direction: "Север",
    cargoType: "Металл",
    zone: "88",
    shift: "Ночь",
    loadCapacity: 95,
    urgency: "высокая",
    equipmentAvailable: false,
    countryFrom: "Китай",
    forwarder: "КеденТрансСервис",
  },
];
